import { NextRequest, NextResponse } from 'next/server'
import dbConnect from '@/lib/mongodb'
import ProductDetail from '@/models/ProductDetail'
import Product from '@/models/Product'

// GET - Fetch all product details
export async function GET(request: NextRequest) {
  try {
    await dbConnect()
    
    const { searchParams } = new URL(request.url)
    const page = parseInt(searchParams.get('page') || '1')
    const limit = parseInt(searchParams.get('limit') || '10')
    const search = searchParams.get('search') || ''
    
    const skip = (page - 1) * limit
    
    // Build aggregation pipeline
    const pipeline: any[] = [
      {
        $lookup: {
          from: 'products',
          localField: 'productId',
          foreignField: '_id',
          as: 'product'
        }
      },
      {
        $unwind: '$product'
      }
    ]
    
    // Add search filter if provided
    if (search) {
      pipeline.push({
        $match: {
          $or: [
            { 'product.name': { $regex: search, $options: 'i' } },
            { 'product.category': { $regex: search, $options: 'i' } },
            { 'seo.focusKeyword': { $regex: search, $options: 'i' } }
          ]
        }
      })
    }
    
    // Add pagination
    pipeline.push(
      { $sort: { createdAt: -1 } },
      { $skip: skip },
      { $limit: limit }
    )
    
    const productDetails = await ProductDetail.aggregate(pipeline)
    
    // Get total count
    const countPipeline = [...pipeline.slice(0, -2)]
    const totalCount = await ProductDetail.aggregate([
      ...countPipeline,
      { $count: 'total' }
    ])
    
    const totalProducts = totalCount[0]?.total || 0
    const totalPages = Math.ceil(totalProducts / limit)
    
    return NextResponse.json({
      success: true,
      productDetails,
      pagination: {
        currentPage: page,
        totalPages,
        totalProducts,
        hasNextPage: page < totalPages,
        hasPrevPage: page > 1
      }
    })

  } catch (error) {
    console.error('Product details fetch error:', error)
    return NextResponse.json(
      { error: 'Failed to fetch product details' },
      { status: 500 }
    )
  }
}

// POST - Create new product details
export async function POST(request: NextRequest) {
  try {
    await dbConnect()
    
    const body = await request.json()
    const {
      productId,
      longDescription,
      featureImages,
      specifications,
      features,
      reviews,
      seo
    } = body
    
    // Validate required fields
    if (!productId || !longDescription || !seo?.focusKeyword) {
      return NextResponse.json(
        { error: 'Product ID, long description, and SEO focus keyword are required' },
        { status: 400 }
      )
    }
    
    // Check if product exists
    const product = await Product.findById(productId)
    if (!product) {
      return NextResponse.json(
        { error: 'Product not found' },
        { status: 404 }
      )
    }
    
    // Check if product details already exist
    const existingDetails = await ProductDetail.findOne({ productId })
    if (existingDetails) {
      return NextResponse.json(
        { error: 'Product details already exist for this product' },
        { status: 400 }
      )
    }
    
    // Auto-generate SEO if not provided
    const autoGeneratedSeo = {
      focusKeyword: seo.focusKeyword,
      title: seo.title || `${seo.focusKeyword || product.name} - ${product.name} | ${product.category} Security Solutions`,
      description: seo.description || `${seo.focusKeyword ? seo.focusKeyword + ': ' : ''}${longDescription.substring(0, 120)}... Professional security solutions.`,
      keywords: seo.keywords && seo.keywords.length > 0 ? seo.keywords : [
        seo.focusKeyword,
        product.name.toLowerCase(),
        product.category.toLowerCase(),
        product.subCategory?.toLowerCase(),
        'security camera',
        'surveillance system',
        'hikvision',
        'professional security',
        'cctv camera'
      ].filter(Boolean)
    }
    
    // Create new product details
    const productDetail = new ProductDetail({
      productId,
      longDescription,
      featureImages: featureImages || [],
      specifications: specifications || [],
      features: features || [],
      reviews: reviews || [],
      seo: autoGeneratedSeo
    })
    
    await productDetail.save()
    
    // Populate product data for response
    await productDetail.populate('productId')
    
    return NextResponse.json({
      success: true,
      message: 'Product details created successfully',
      productDetail
    }, { status: 201 })

  } catch (error) {
    console.error('Product details creation error:', error)
    return NextResponse.json(
      { error: 'Failed to create product details' },
      { status: 500 }
    )
  }
}